import '@wg-plus/components/base/style'
import '@wg-plus/components/input/style'
import '@wg-plus/components/tag/style'
import '@wg-plus/components/option/style'
import '@wg-plus/components/option-group/style'
import '@wg-plus/components/scrollbar/style'
import '@wg-plus/components/popper/style'
import '@wg-plus/theme-chalk/src/select.scss'
